name: Check PR
on:
  pull_request:
    branches:
      - main
    types:
      - synchronize
      - opened
      - ready_for_review
jobs:
  check-status:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
